import {
  CrisisEvent,
  ResourceUnit,
  IntelFeedItem,
  PredictionMetric,
  RegionData,
  KpiMetric,
} from "@/app/types";

export const crisisEvents: CrisisEvent[] = [
  {
    id: "CRZ-2026-0847",
    title: "Eastern Mediterranean Naval Standoff",
    region: "AOR-EASTMED",
    coordinates: [35.5, 28.0],
    threatLevel: "HIGH",
    category: "MARITIME",
    description:
      "Increased naval presence detected in Eastern Mediterranean. Three carrier strike groups repositioning. Air defense systems on elevated readiness.",
    timestamp: "2026-07-16T14:30:00Z",
    confidence: 0.94,
    sources: ["SIGINT", "IMINT", "HUMINT"],
  },
  {
    id: "CRZ-2026-0846",
    title: "Baltic Cyber Infrastructure Attack",
    region: "AOR-BALTIC",
    coordinates: [56.9, 24.1],
    threatLevel: "CRITICAL",
    category: "CYBER",
    description:
      "Coordinated APT campaign targeting critical infrastructure across Baltic states. Power grid anomalies detected. Attribution: APT29 variant.",
    timestamp: "2026-07-16T12:15:00Z",
    confidence: 0.91,
    sources: ["CYBERCOM", "NCSC", "THREAT_INTEL"],
  },
  {
    id: "CRZ-2026-0845",
    title: "Sahel Humanitarian Corridor Disruption",
    region: "AOR-SAHEL",
    coordinates: [17.0, 1.0],
    threatLevel: "MODERATE",
    category: "HUMANITARIAN",
    description:
      "Armed group activity disrupting aid corridors in Mali-Niger border region. 12,000 civilians affected. UN convoy rerouted.",
    timestamp: "2026-07-16T09:45:00Z",
    confidence: 0.87,
    sources: ["UNOCHA", "NGO_REPORTS", "SATELLITE"],
  },
  {
    id: "CRZ-2026-0844",
    title: "South China Sea Freedom of Navigation Incident",
    region: "AOR-INDOPAC",
    coordinates: [12.0, 114.0],
    threatLevel: "HIGH",
    category: "MARITIME",
    description:
      "Unsafe maneuver by PLAN vessel during FONOP operation. Closest point of approach: 45 meters. Diplomatic protest filed.",
    timestamp: "2026-07-16T08:20:00Z",
    confidence: 0.96,
    sources: ["7TH_FLEET", "SATELLITE", "AIS"],
  },
  {
    id: "CRZ-2026-0843",
    title: "Arctic SAR Operation - Missing Research Vessel",
    region: "AOR-ARCTIC",
    coordinates: [78.5, -15.0],
    threatLevel: "MODERATE",
    category: "SAR",
    description:
      "Norwegian research vessel overdue by 72 hours. Last known position: 78°30'N 15°00'W. Joint SAR operation initiated.",
    timestamp: "2026-07-15T22:00:00Z",
    confidence: 0.82,
    sources: ["JRCC", "SATELLITE", "COAST_GUARD"],
  },
  {
    id: "CRZ-2026-0842",
    title: "FLASH: Eastern European Border Mobilization",
    region: "AOR-EASTEU",
    coordinates: [50.4, 30.5],
    threatLevel: "FLASH",
    category: "CONVENTIONAL",
    description:
      "Large-scale mechanized unit movement detected near border. Satellite imagery confirms division-level redeployment. NATO alert level elevated to DEFCON 3.",
    timestamp: "2026-07-16T16:00:00Z",
    confidence: 0.98,
    sources: ["SATELLITE", "SIGINT", "HUMINT", "OSINT"],
  },
  {
    id: "CRZ-2026-0841",
    title: "Horn of Africa Piracy Resurgence",
    region: "AOR-HOA",
    coordinates: [12.0, 48.0],
    threatLevel: "HIGH",
    category: "MARITIME",
    description:
      "Three vessel hijackings in Gulf of Aden within 48 hours. Combined Maritime Forces increasing patrols. Insurance premiums spiking.",
    timestamp: "2026-07-16T06:00:00Z",
    confidence: 0.89,
    sources: ["CMF", "UKMTO", "INSURANCE"],
  },
  {
    id: "CRZ-2026-0840",
    title: "Pacific Ring of Fire Seismic Event",
    region: "AOR-INDOPAC",
    coordinates: [-6.0, 155.0],
    threatLevel: "MODERATE",
    category: "NATURAL",
    description:
      "Magnitude 7.2 earthquake near Solomon Islands. Tsunami warning issued for regional archipelagos. Humanitarian pre-positioning initiated.",
    timestamp: "2026-07-16T04:30:00Z",
    confidence: 0.99,
    sources: ["USGS", "PTWC", "UNOCHA"],
  },
];

export const resourceUnits: ResourceUnit[] = [
  {
    id: "TF-ALPHA",
    name: "Task Force Alpha",
    type: "Naval Strike Group",
    status: "DEPLOYED",
    location: "Eastern Mediterranean",
    coordinates: [35.5, 28.0],
    personnel: 4500,
    readiness: 94,
    eta: "ON STATION",
    mission: "Deterrence & Freedom of Navigation",
  },
  {
    id: "CYBER-1",
    name: "Cyber Defense Cell",
    type: "Cyber Operations",
    status: "DEPLOYED",
    location: "Tallinn, Estonia",
    coordinates: [59.4, 24.7],
    personnel: 120,
    readiness: 98,
    eta: "ON STATION",
    mission: "Baltic Infrastructure Defense",
  },
  {
    id: "SAR-NORTH",
    name: "Arctic SAR Detachment",
    type: "Search & Rescue",
    status: "DEPLOYED",
    location: "Svalbard, Norway",
    coordinates: [78.2, 15.6],
    personnel: 45,
    readiness: 87,
    eta: "ON STATION",
    mission: "Missing Vessel Search Operation",
  },
  {
    id: "QRF-EUROPE",
    name: "Quick Reaction Force Europe",
    type: "Mechanized Infantry",
    status: "STAGING",
    location: "Poland",
    coordinates: [52.2, 21.0],
    personnel: 3200,
    readiness: 76,
    eta: "6 HOURS",
    mission: "Eastern Border Reinforcement",
  },
  {
    id: "AEGIS-PAC",
    name: "AEGIS Pacific",
    type: "Missile Defense",
    status: "DEPLOYED",
    location: "Guam",
    coordinates: [13.4, 144.8],
    personnel: 800,
    readiness: 99,
    eta: "ON STATION",
    mission: "Indo-Pacific Missile Defense",
  },
  {
    id: "HADR-SAHEL",
    name: "Humanitarian Response Team",
    type: "Medical & Logistics",
    status: "STAGING",
    location: "Niamey, Niger",
    coordinates: [13.5, 2.1],
    personnel: 180,
    readiness: 65,
    eta: "12 HOURS",
    mission: "Sahel Corridor Security & Aid",
  },
  {
    id: "SOF-RECCE",
    name: "Special Operations Recon",
    type: "Special Forces",
    status: "STANDBY",
    location: "Undisclosed",
    coordinates: [0, 0],
    personnel: 24,
    readiness: 100,
    eta: "2 HOURS",
    mission: "Classified",
  },
  {
    id: "DRONE-WING",
    name: "ISR Drone Wing",
    type: "Unmanned Aerial Systems",
    status: "DEPLOYED",
    location: "Djibouti",
    coordinates: [11.6, 43.1],
    personnel: 60,
    readiness: 92,
    eta: "ON STATION",
    mission: "Horn of Africa Maritime Surveillance",
  },
  {
    id: "ENG-CORPS",
    name: "Engineering Corps",
    type: "Combat Engineering",
    status: "STANDBY",
    location: "Germany",
    coordinates: [50.1, 8.7],
    personnel: 500,
    readiness: 88,
    eta: "24 HOURS",
    mission: "Infrastructure Hardening",
  },
];

export const intelFeed: IntelFeedItem[] = [
  {
    id: "INT-2026-1247",
    classification: "TOP SECRET",
    timestamp: "2026-07-16T16:00:00Z",
    source: "NRO / SIGINT",
    headline: "Division-Level Armor Movement Confirmed",
    summary:
      "Satellite imagery confirms 3rd Guards Tank Army repositioning within 15km of border. Estimated 400 MBTs, 200 IFVs. NATO JFC Brunssum activated.",
    confidence: 0.98,
    region: "AOR-EASTEU",
    tags: ["ARMOR", "MOBILIZATION", "DEFCON-3"],
  },
  {
    id: "INT-2026-1246",
    classification: "SECRET",
    timestamp: "2026-07-16T14:30:00Z",
    source: "CYBERCOM / NCSC",
    headline: "APT29 Infrastructure Mapped",
    summary:
      "Active counter-intrusion operation mapped C2 infrastructure for Baltic cyber campaign. 47 nodes identified across 12 jurisdictions. Takedown coordinated.",
    confidence: 0.91,
    region: "AOR-BALTIC",
    tags: ["CYBER", "APT29", "C2"],
  },
  {
    id: "INT-2026-1245",
    classification: "SECRET",
    timestamp: "2026-07-16T12:15:00Z",
    source: "7TH FLEET / N2",
    headline: "PLAN Vessel Tracking Analysis",
    summary:
      "Analysis of unsafe maneuver reveals deliberate provocation pattern. Similar incidents logged 3x in past 72 hours. Rules of engagement under review.",
    confidence: 0.94,
    region: "AOR-INDOPAC",
    tags: ["MARITIME", "FONOP", "PROVOCATION"],
  },
  {
    id: "INT-2026-1244",
    classification: "CONFIDENTIAL",
    timestamp: "2026-07-16T10:00:00Z",
    source: "UNOCHA / FIELD REPORT",
    headline: "Sahel Aid Corridor Status Update",
    summary:
      "NGO convoy successfully rerouted via alternate corridor. 8,000 civilians reached with supplies. Remaining 4,000 in inaccessible zone pending SOF escort.",
    confidence: 0.85,
    region: "AOR-SAHEL",
    tags: ["HUMANITARIAN", "CONVOY", "ACCESS"],
  },
  {
    id: "INT-2026-1243",
    classification: "SECRET",
    timestamp: "2026-07-16T08:30:00Z",
    source: "DIA / HUMINT",
    headline: "Regional Actor Diplomatic Channels Active",
    summary:
      "Back-channel communications detected between regional actors. Mediation proposal via third party under consideration. De-escalation window: 48-72 hours.",
    confidence: 0.72,
    region: "AOR-EASTMED",
    tags: ["DIPLOMACY", "BACKCHANNEL", "DE-ESCALATION"],
  },
  {
    id: "INT-2026-1242",
    classification: "CONFIDENTIAL",
    timestamp: "2026-07-16T06:00:00Z",
    source: "UKMTO / CMF",
    headline: "Gulf of Aden Piracy Pattern Analysis",
    summary:
      "Three hijackings show coordinated tactics: mothership-daughter boat configuration. Intelligence suggests single criminal network. Maritime patrols expanded.",
    confidence: 0.88,
    region: "AOR-HOA",
    tags: ["PIRACY", "MARITIME", "PATTERN"],
  },
  {
    id: "INT-2026-1241",
    classification: "UNCLASSIFIED",
    timestamp: "2026-07-16T04:00:00Z",
    source: "USGS / GEOPHYSICAL",
    headline: "Solomon Islands Aftershock Sequence",
    summary:
      "Aftershock sequence continues with 23 events >M4.5 in past 6 hours. Mainshock re-evaluated to M7.4. Tsunami threat downgraded. Damage assessment ongoing.",
    confidence: 0.99,
    region: "AOR-INDOPAC",
    tags: ["NATURAL", "SEISMIC", "TSUNAMI"],
  },
];

export const predictionMetrics: PredictionMetric[] = [
  {
    label: "Eastern Europe Escalation",
    probability: 0.73,
    trend: [0.45, 0.52, 0.58, 0.61, 0.67, 0.71, 0.73],
    timeframe: "72H",
  },
  {
    label: "Cyber Campaign Expansion",
    probability: 0.68,
    trend: [0.55, 0.57, 0.60, 0.62, 0.65, 0.67, 0.68],
    timeframe: "48H",
  },
  {
    label: "Maritime Incident (SCS)",
    probability: 0.41,
    trend: [0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41],
    timeframe: "96H",
  },
  {
    label: "Humanitarian Crisis (Sahel)",
    probability: 0.56,
    trend: [0.42, 0.45, 0.48, 0.50, 0.52, 0.54, 0.56],
    timeframe: "7D",
  },
  {
    label: "Arctic SAR Resolution",
    probability: 0.34,
    trend: [0.20, 0.22, 0.25, 0.28, 0.30, 0.32, 0.34],
    timeframe: "48H",
  },
];

export const regionData: RegionData[] = [
  {
    id: "AOR-EASTEU",
    name: "Eastern Europe",
    aor: "JFC Brunssum",
    threatLevel: "FLASH",
    activeCrises: 1,
    personnelDeployed: 3200,
    lastUpdate: "2026-07-16T16:00:00Z",
  },
  {
    id: "AOR-BALTIC",
    name: "Baltic States",
    aor: "MNC NE",
    threatLevel: "CRITICAL",
    activeCrises: 1,
    personnelDeployed: 120,
    lastUpdate: "2026-07-16T12:15:00Z",
  },
  {
    id: "AOR-EASTMED",
    name: "Eastern Mediterranean",
    aor: "JFC Naples",
    threatLevel: "HIGH",
    activeCrises: 1,
    personnelDeployed: 4500,
    lastUpdate: "2026-07-16T14:30:00Z",
  },
  {
    id: "AOR-INDOPAC",
    name: "Indo-Pacific",
    aor: "USPACOM",
    threatLevel: "HIGH",
    activeCrises: 2,
    personnelDeployed: 860,
    lastUpdate: "2026-07-16T08:20:00Z",
  },
  {
    id: "AOR-SAHEL",
    name: "Sahel Region",
    aor: "AFRICOM",
    threatLevel: "MODERATE",
    activeCrises: 1,
    personnelDeployed: 180,
    lastUpdate: "2026-07-16T09:45:00Z",
  },
  {
    id: "AOR-HOA",
    name: "Horn of Africa",
    aor: "CJTF-HOA",
    threatLevel: "HIGH",
    activeCrises: 1,
    personnelDeployed: 60,
    lastUpdate: "2026-07-16T06:00:00Z",
  },
  {
    id: "AOR-ARCTIC",
    name: "Arctic",
    aor: "JFC Norfolk",
    threatLevel: "MODERATE",
    activeCrises: 1,
    personnelDeployed: 45,
    lastUpdate: "2026-07-15T22:00:00Z",
  },
];

export const kpiMetrics: KpiMetric[] = [
  { label: "Active Crises", value: 8, change: 2, trend: "up", unit: "" },
  { label: "Personnel Deployed", value: "9,065", change: 12, trend: "up", unit: "" },
  { label: "Threat Level", value: "FLASH", change: 0, trend: "up", unit: "" },
  { label: "Intel Reports (24H)", value: 247, change: -3, trend: "down", unit: "" },
  { label: "Resource Readiness", value: "87.3%", change: 1.2, trend: "up", unit: "" },
  { label: "Prediction Accuracy", value: "91.4%", change: 0.8, trend: "up", unit: "" },
];

export const worldMapPaths = {
  // Simplified world map SVG paths for major landmasses
  regions: [
    {
      id: "na",
      name: "North America",
      path: "M50,80 L280,60 L320,120 L300,200 L200,220 L100,180 L50,80Z",
      crises: 0,
    },
    {
      id: "sa",
      name: "South America",
      path: "M220,240 L320,230 L340,320 L280,420 L240,380 L220,240Z",
      crises: 0,
    },
    {
      id: "eu",
      name: "Europe",
      path: "M420,60 L520,50 L560,90 L540,140 L480,150 L440,130 L420,60Z",
      crises: 3,
    },
    {
      id: "af",
      name: "Africa",
      path: "M440,160 L540,150 L580,220 L560,320 L500,360 L460,300 L440,220 L440,160Z",
      crises: 2,
    },
    {
      id: "as",
      name: "Asia",
      path: "M560,50 L780,40 L860,100 L840,200 L720,220 L640,180 L580,120 L560,50Z",
      crises: 2,
    },
    {
      id: "au",
      name: "Australia",
      path: "M720,300 L820,290 L840,350 L780,380 L720,360 L720,300Z",
      crises: 0,
    },
  ],
};
